CREATE TABLE "ROLES"
(
    "ID" VARCHAR2(32) DEFAULT SYS_GUID(),
	"NAME" VARCHAR2(64),
    CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID")
);

CREATE TABLE "DEPARTMENTS"
(
    "ID" VARCHAR2(32) DEFAULT SYS_GUID(),
	"NAME" VARCHAR2(256),
	"MANAGER_ID" VARCHAR2(32),
    CONSTRAINT "DEPARTMENTS_PK" PRIMARY KEY ("ID")
);


CREATE TABLE "EMPLOYEES"
(
    "ID" VARCHAR2(32) DEFAULT SYS_GUID(),
	"NAME" VARCHAR2(256),
	"PHONE_NUMBER" VARCHAR2(64),
	"ROLE_ID" VARCHAR2(64),
	"DEPARTMENT_ID" VARCHAR2(64),
    CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("ID"),
    FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENTS" ("ID")
);

ALTER TABLE "DEPARTMENTS" ADD CONSTRAINT "MANAGER_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES "EMPLOYEES" ("ID");

CREATE TABLE "SALARY"
(
    "DEPARTMENT_ID" VARCHAR2(32),
	"ROLE_ID" VARCHAR2(32),
	"SALARY" NUMBER,
    CONSTRAINT "SALARY_PK" PRIMARY KEY ("DEPARTMENT_ID", "ROLE_ID"),
    FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENTS" ("ID"),
    FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES" ("ID")
);

CREATE TABLE "TYPES"
(
    "ID" VARCHAR2(32) DEFAULT SYS_GUID(),
	"NAME" VARCHAR2(256),
    CONSTRAINT "TYPES_PK" PRIMARY KEY ("ID")
);

CREATE TABLE "STORE"
(
    "ID" VARCHAR2(32) DEFAULT SYS_GUID(),
	"NAME" VARCHAR2(256),
	"LOCATION" VARCHAR2(256),
    CONSTRAINT "STORE_PK" PRIMARY KEY ("ID")
);

CREATE TABLE "PRODUCTS"
(
    "ID" VARCHAR2(32) DEFAULT SYS_GUID(),
	"NAME" VARCHAR2(256),
	"CATEGORY" VARCHAR2(256),
	"QUALITY" VARCHAR2(256),
	"PRICE" NUMBER,
	"IMAGE" VARCHAR2(256),
	"STATUS" VARCHAR2(64),
	"TYPE_ID" VARCHAR2(32),
	"STORE_ID" VARCHAR2(32),
	"CREATION_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TYPE_ID" PRIMARY KEY ("ID"),
    FOREIGN KEY ("TYPE_ID") REFERENCES "TYPES" ("ID"),
    FOREIGN KEY ("STORE_ID") REFERENCES "STORE" ("ID")
);

CREATE TABLE "PRODUCT_EMPLOYEE"
(
    "PRODUCT_ID" VARCHAR2(32),
	"EMPLOYEE_ID" VARCHAR2(32),
	"CREATION_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PRODUCT_EMPLOYEE_PK" PRIMARY KEY ("PRODUCT_ID", "EMPLOYEE_ID"),
    FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCTS" ("ID"),
    FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEES" ("ID")
);